version: '3.4'

services:
  primary:
    build:
      context: ./build/
    command: --bind_ip_all --logpath /data/logs/mongod.log --replSet $REPLICASET_NAME
    ports:
      - "127.0.0.1:30001:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=$ROOT_USER
    #   - MONGO_INITDB_ROOT_PASSWORD=$ROOT_PASSWD
    env_file:
      - .env
    volumes:
      - ./primary_db:/data/db
    restart: always
  
  secondary_01:
    build:
      context: ./build/
    command: --bind_ip_all --logpath /data/logs/mongod.log --replSet $REPLICASET_NAME
    ports:
      - "127.0.0.1:30002:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=$ROOT_USER
    #   - MONGO_INITDB_ROOT_PASSWORD=$ROOT_PASSWD
    env_file:
      - .env
    volumes:
      - ./secondary_01_db:/data/db
    restart: always

  secondary_02:
    build:
      context: ./build/
    command: --bind_ip_all --logpath /data/logs/mongod.log --replSet $REPLICASET_NAME
    ports:
      - "127.0.0.1:30003:27017"
    env_file:
      - .env
    volumes:
      - ./secondary_02_db:/data/db
    restart: always

  setup:
    build:
      context: ./build/
    depends_on:
      - primary
      - secondary_01
      - secondary_02
    env_file:
      - .env
    volumes:
      - ./build/entrypoint/docker-entrypoint.sh:/data/entrypoint/docker-entrypoint.sh
    entrypoint: /data/entrypoint/docker-entrypoint.sh